version: '3'

services:

  api:
    hostname: iot-data-generator-api
    image: pdrivom/iot-data-generator:v1
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src/api:/usr/src/api
    networks:
      - api

networks:
  api:
    driver: bridge