version: '3'

services:

  api:
    hostname: iot-data-generator-api
    image: pdrivom/iot-data-generator:latest
    ports:
      - 8000:8000
    volumes:
      - iot-data-generator:/usr/src/api
    networks:
      - api

volumes:
  iot-data-generator:

networks:
  api:
    driver: bridge