version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - dev_env

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dev_env
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:9092 --list
      interval: 30s
      timeout: 20s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - dev_env

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    volumes:
      - ./configs/mosquitto:/mosquitto/config:rw
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - dev_env

  api:
    hostname: iot-data-generator-api
    image: pdrivom/iot-data-generator:v1
    depends_on:
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      mosquitto:
        condition: service_started
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./api:/usr/src/api
    networks:
      - api
      - dev_env

networks:
  api:
  dev_env:
    driver: bridge