---
name: Checks

on: [push]

env:
  DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
  DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  
jobs:
  test-not-lint:
    name: Test but not Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $DOCKER_USER
          password: $DOCKERHUB_TOKEN
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        working-directory: ./src
        run: docker-compose up -d && docker-compose run --rm api sh -c "pytest"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%M%S')"
      - name: Build the Docker image
        working-directory: ./src
        run: docker build . --file Dockerfile --tag $DOCKER_USER/iot-data-generator:${{ steps.date.outputs.date }}  
      - name: Docker Push
        run: docker push $DOCKER_USER/iot-data-generator:${{ steps.date.outputs.date }}  
